Run iggy-server via iggy-bench
iggy-rs/iggy pull request #212
Opened 2023-10-24 15:50 UTC by hubcio

This closes #135.

2023-10-24 16:38 UTC, BartoszCiesla approved these changes

2023-10-25 09:42 UTC, BartoszCiesla submitted a review, later dismissed

2023-10-26 14:52 UTC, spetz requested changes

2023-10-26 14:52 UTC, spetz commented on bench/src/benchmark_runner.rs
> +    let default_config: ServerConfig =
Maybe this path could be also optionally provided via args and/or env var - for example, when the user simply wants to run the benchmarks as already compiled executable file from the different location?

2023-10-26 14:52 UTC, spetz commented on bench/src/benchmark_runner.rs
> +        let mut test_server = TestServer::new(Some(envs));
Let's make the cleanup optional - by doing so, we could simply start e.g. polling benchmark multiple times, without a need to run the send benchmark first.

2023-10-26 14:52 UTC, spetz commented on integration/src/test_server.rs
>      pub fn create(files_path: String, envs: Option<HashMap<String, String>>) -> Self {
The path is always random, which works fine for the regular tests. In case of benchmark, we could also provide the optional path from args/env (directly, or loaded previously from the provided server config file) - this would help with running the same bench multiple times e.g. polling the messages using the already existing data.

2023-10-26 18:43 UTC, hubcio commented on bench/src/benchmark_runner.rs
> +    let default_config: ServerConfig =
Done, in next update path will be provided as argument to bench
`--server-executable-path`

2023-10-26 18:55 UTC, hubcio commented on bench/src/benchmark_runner.rs
> +        let mut test_server = TestServer::new(Some(envs));
Done, in next update there will be new argument to bench
`-c / --cleanup`

2023-10-26 19:01 UTC, hubcio commented on integration/src/test_server.rs
>      pub fn create(files_path: String, envs: Option<HashMap<String, String>>) -> Self {
Done, in next update local_data will stay the same as before.

2023-10-29 09:01 UTC, spetz commented on integration/src/test_server.rs
> +        if !self.cleanup {
I'd always stop the server, and use the cleanup only to remove the local data.

2023-10-29 09:08 UTC, spetz commented
Let's also update the main readme file :)

2023-10-29 12:26 UTC, spetz approved these changes
Works great, well done :D

2023-10-29 17:16 UTC, spetz requested changes

2023-10-29 17:16 UTC, spetz commented on bench/src/args/kind.rs
> +/// Polling (reading) benchmark
Should be "Sending (writing)"

2023-10-29 17:16 UTC, spetz commented on bench/src/args/kind.rs
> +/// Polling (writing) benchmark
Should be Polling (reading)

2023-10-29 18:09 UTC, spetz approved these changes

2023-10-29 20:58 UTC, merged