implement Display for Partition, Segment and Stream
iggy-rs/iggy pull request #488
Opened 2024-01-07 12:34 UTC by berendsliedrecht

- Implemented `fmt::Display` for `Partition`, `Segment` and `Stream`
- Renamed `XXX_indexes` to `XXX_indices`
- Renamed `topics_ids` to `topic_ids`
- Closes #481

2024-01-07 12:42 UTC, hubcio requested changes

2024-01-07 12:42 UTC, hubcio commented on server/src/streaming/partitions/messages.rs
> +            let time_indexes = segment.time_indices.as_ref().unwrap();
let time_indices

2024-01-07 12:45 UTC, hubcio commented
@berendsliedrecht please take a look at discord 🦀

2024-01-07 12:54 UTC, hubcio commented
![image](https://github.com/iggy-rs/iggy/assets/5490304/c6832a49-b195-4436-adbe-8aff04a2cfd3)

2024-01-12 14:27 UTC, hubcio commented
hey @berendsliedrecht, any plans to continue?

2024-11-03 15:21 UTC, closed without merging

2025-04-13 01:09 UTC, ynachi commented
@hubcio, I would like to take this one if still relevant and available.

2025-04-14 20:18 UTC, hubcio commented
> @hubcio, I would like to take this one if still relevant and available.

hey, yes, it's available. sorry for late reply, better join our discord to get instant replies :)